from pathlib import Path
import re
import unittest


ROOT = Path(__file__).resolve().parents[1]


class TMDBOnlyContractTests(unittest.TestCase):
    def read(self, relative: str) -> str:
        return (ROOT / relative).read_text(encoding='utf-8')

    def assert_css_rule_has(self, css: str, selector: str, *declarations: str) -> None:
        rule_bodies = re.findall(
            rf'{re.escape(selector)}(?=\s*(?:,|\{{))[^{{}}]*\{{([^{{}}]*)\}}',
            css,
        )
        self.assertTrue(rule_bodies, f'Missing CSS rule for {selector}')

        def normalize(value: str) -> str:
            compact = re.sub(r'\s+', '', value)
            return re.sub(
                r'hsla\(0,0%,100%,([^)]+)\)',
                r'rgba(255,255,255,\1)',
                compact,
            )

        expected = [normalize(declaration).rstrip(';') for declaration in declarations]
        self.assertTrue(
            any(
                all(declaration in normalize(body) for declaration in expected)
                for body in rule_bodies
            ),
            f'{selector} is missing CSS declarations: {declarations}',
        )

    def test_source_section_removed(self):
        ui = self.read('static/js/ui.js')
        settings = self.read('static/js/settings.js')
        data_settings = self.read('frontend/src/settings/SettingsData.vue')
        self.assertNotIn('Metadata ' + 'Source', settings)
        self.assertNotIn('Artwork ' + 'Source', ui)
        self.assertNotIn('<h2>SOURCE</h2>', ui)
        self.assertIn('Export, import, or create a readable report', data_settings)
        self.assertNotIn('Simkl / Trakt', data_settings)

    def test_episode_logging_auto_completion_rules_exist(self):
        app_js = self.read('static/js/app.js')
        self.assertIn('async function autoCompleteShowAfterLogging(show)', app_js)
        self.assertIn('async function verifyRegularEpisodeCompletionData(show)', app_js)
        self.assertIn('function hasKnownFutureRegularEpisode(show)', app_js)
        self.assertIn('function reopenCompletedShowAfterUnwatch(show,seasonNumber)', app_js)
        self.assertEqual(app_js.count('await autoCompleteShowAfterLogging(show);'), 5)
        self.assertEqual(app_js.count('reopenCompletedShowAfterUnwatch(show,'), 3)
        self.assertIn('show.status === "paused"', app_js)
        self.assertIn('show.status === "dropped"', app_js)

    def test_episode_detail_page_rebuild_matches_show_page_language(self):
        ui = self.read('static/js/ui.js')
        app_js = self.read('static/js/app.js')
        css = self.read('static/css/tailwind-input.css')
        episode_render = ui[ui.index('function renderEpisodeModal'):ui.index('function formatEpisodeWatchedDate')]

        self.assertIn('episode-page-rebuild', episode_render)
        self.assertIn('show-page-hero-shell episode-page-hero-shell', episode_render)
        self.assertIn('episodeData.still_path || show.backdrop_path || ""', episode_render)
        self.assertIn('PREVIOUS EPISODE', episode_render)
        self.assertIn('NEXT EPISODE', episode_render)
        self.assertIn('MARK UNWATCHED', episode_render)
        self.assertNotIn('releaseTimeText', episode_render)
        self.assertIn('renderV2EpisodeLinksHTML', episode_render)
        self.assertIn('Guest Stars', ui)
        self.assertIn('_episode_guest_stars', app_js)
        self.assertIn('_episode_cast_credits', app_js)
        self.assertIn('normalizeTMDBEpisodeCreditGroups', app_js)
        self.assertIn('.episode-page-status-card.watched', css)

    def test_source_provider_script_removed_from_template(self):
        template = self.read('templates/index.html')
        self.assertNotIn('source-' + 'provider.js', template)
        self.assertIn('2.0-tailwind', template)
        self.assertIn('app-router.js', template)
        self.assertNotIn('static-adapter.js', template)

    def test_backend_proxy_is_tmdb_only(self):
        routes = self.read('tvtracker/web/routes.py')
        self.assertIn('/api/tmdb/<path:tmdb_path>', routes)
        self.assertNotIn('api.' + 'tv' + 'maze.com', routes)
        self.assertNotIn('api.' + 'tv' + 'maze.com', self.read('app.py'))

    def test_legacy_metadata_cleanup_exists(self):
        app_py = self.read('app.py')
        app_js = self.read('static/js/app.js')
        self.assertIn('clean_legacy_metadata', app_py)
        self.assertIn('cleanLegacyMetadata', app_js)

    def test_empty_season_has_final_empty_state(self):
        show_details_bridge = self.read('static/js/show-details-vue-bridge.js')
        app_js = self.read('static/js/app.js')
        self.assertIn('Episode list not announced yet.', show_details_bridge)
        self.assertIn('Loading episode list...', show_details_bridge)
        self.assertIn('function seasonIsLoadedEmpty(show,seasonNumber)', show_details_bridge)
        self.assertIn('Number(show._season_episodes[seasonKey] || 0) === 0', app_js)


    def test_watch_log_integrity_repair_exists(self):
        app_js = self.read('static/js/app.js')
        app_py = self.read('app.py')
        self.assertIn('getDeterministicHistoryId', app_js)
        self.assertIn('normalizeTrackerDataForEpisodeIntegrity', app_js)
        self.assertIn('removeExistingHistoryEntriesForEpisode', app_js)
        self.assertIn('isEpisodeLoggable', app_js)
        self.assertIn('dedupe_history_by_episode', app_py)
        self.assertIn('find_logical_duplicate_history_ids', app_py)

    def test_discover_description_and_view_more_polish_exists(self):
        search_vue = self.read('frontend/src/search-discover/SearchResults.vue')
        css = self.read('static/css/tailwind-input.css')
        app_js = self.read('static/js/app.js')
        tmdb_js = self.read('static/js/tmdb.js')
        self.assertIn('VIEW MORE', search_vue)
        self.assertIn('loadMoreSearchResults', app_js)
        self.assertIn('loadMoreDiscoverSection', app_js)
        self.assertIn('-webkit-line-clamp:2', css)
        self.assertIn('view-more-button', css)
        self.assertIn('tmdbSearchShowsPage', tmdb_js)

    def test_frontend_uses_tailwind_only_assets(self):
        template = "\n".join([
            self.read('templates/index.html'),
            self.read('templates/login.html'),
            self.read('templates/error.html'),
        ])
        ui = self.read('static/js/ui.js')
        self.assertIn('tailwind.css', template)
        self.assertIn('2.0-tailwind', template)
        self.assertNotIn('2.0-integration', template)
        self.assertNotIn('bootstrap.min.css', template)
        self.assertNotIn('bootstrap.bundle.min.js', template)
        self.assertNotIn('css/style.css', template)
        self.assertNotIn('css/foundation.css', template)
        self.assertNotIn('js/shell.js', template)
        self.assertNotIn('window.bootstrap', ui)
        self.assertFalse((ROOT / 'static/css/style.css').exists())
        self.assertFalse((ROOT / 'static/css/foundation.css').exists())
        self.assertFalse((ROOT / 'static/js/shell.js').exists())
        self.assertFalse((ROOT / 'static/assets/favicon.svg').exists())
        self.assertFalse((ROOT / 'static/assets/WATCH TIME.svg').exists())
        self.assertFalse((ROOT / 'static/assets/EPISODES WATCHED.svg').exists())

    def test_tailwind_preserves_legacy_layout_reset(self):
        css = self.read('static/css/tailwind-input.css')
        self.assertIn('margin:0;', css)
        self.assertIn('padding:0;', css)
        self.assertIn('@apply tw-mt-auto tw-mb-[30px];', css)

    def test_show_page_remove_button_stays_in_status_row(self):
        css = self.read('static/css/tailwind-input.css')
        self.assertIn('.show-page-status-buttons .remove-show-button', css)
        self.assertIn('@apply tw-ml-0;', css)

    def test_real_protected_page_routes_exist(self):
        app_py = self.read('tvtracker/web/routes.py')
        router = self.read('static/js/app-router.js')
        template = self.read('templates/index.html')
        self.assertIn('@app.get("/app/list/<list_slug>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/upcoming", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/history", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/discover", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/discover/<media_type>/<category_slug>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/browse/<media_type>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/search", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/profile", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/settings", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/settings/<settings_section>", strict_slashes=False)', app_py)
        self.assertIn('/app/settings/notifications', router)
        self.assertIn('@app.get("/app/show/<show_key>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/genre/<genre_media>/<genre_slug>", strict_slashes=False)', app_py)
        self.assertNotIn('@app.get("/app/genre/<genre_slug>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/network/<network_key>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/language/<media_type>/<language_code>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/country/<media_type>/<country_code>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/theme/<media_type>/<theme_key>", strict_slashes=False)', app_py)
        self.assertNotIn('@app.get("/app/theme/<theme_key>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/movie/<movie_key>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/company/<media_type>/<company_key>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/provider/<media_type>/<provider_key>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/year/<media_type>/<int:year_value>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/status/<status_slug>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/certification/<media_type>/<certification_slug>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/collections", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/collection/<collection_key>", strict_slashes=False)', app_py)
        self.assertIn('@app.get("/app/person/<person_key>", strict_slashes=False)', app_py)
        self.assertIn('"/app/show/<show_key>/season/<int:season_number>/episode/<int:episode_number>"', app_py)
        self.assertNotIn('@app.get("/app/<path:app_path>")', app_py)
        self.assertIn('/app/list/watching', app_py)
        self.assertIn('app\\/show', router)
        self.assertIn('^\\/app\\/genre\\/', router)
        self.assertIn('/app/search', router)
        self.assertIn('app\\/movie', router)
        self.assertIn('app\\/collection', router)
        self.assertIn('typedDiscoveryIdMatch', router)
        self.assertIn('networkMatch', router)
        self.assertIn('yearMatch', router)
        self.assertIn('statusMatch', router)
        self.assertIn('certificationMatch', router)
        self.assertIn('languageMatch', router)
        self.assertIn('countryMatch', router)
        self.assertIn('app\\/person', router)
        self.assertIn('\\/season\\/', router)
        self.assertIn('\\/episode\\/', router)
        self.assertNotIn('#/app', router)
        self.assertIn('show-detail-page', template)
        self.assertIn('genre-detail-page', template)
        self.assertIn('person-detail-page', template)
        self.assertIn('show-detail-filters.js', template)
        self.assertIn('episode-detail-page', template)
        self.assertIn('openPersonPage', router)
        self.assertNotIn('person|actor|creator|director|writer|producer|editor|composer|cinematographer', router)
        self.assertIn('openDiscoveryFilterPage', router)
        self.assertIn('function parseAppRoute(pathname,search="")', router)
        self.assertIn('function prepareInitialRoute()', router)
        self.assertIn('parseRoute:parseAppRoute', router)
        self.assertIn('prepareInitialRoute();', router)
        self.assertNotIn("initial_nav_shows", template)
        self.assertNotIn("initial_is_detail", template)
        self.assertIn('<div id="shows-page" class="page">', template)
        self.assertIn('class="watchlist-initial-skeleton"', template)
        self.assertIn('function configureInitialListSkeleton(filter)', router)
        self.assertIn('window.addEventListener("popstate"', router)
        self.assertIn('applyRoute("popstate")', router)
        self.assertIn('normalizeCurrentRoute(parsed)', router)
        self.assertNotIn('/app/watchlist', router)
        self.assertFalse((ROOT / 'static/js/v2-router.js').exists())
        tmdb = self.read('static/js/tmdb.js')
        app_js = self.read('static/js/app.js')
        self.assertIn('requestError.status = response.status', tmdb)
        self.assertIn('function isTMDBNotFoundError(error)', app_js)
        self.assertIn('renderAppRouteNotFoundPage();', app_js)
        ui = self.read('static/js/ui.js')
        self.assertIn('renderPersonDetailPage', ui)
        self.assertIn('renderDiscoveryFilterDetailPage', ui)
        movie_details_bridge = self.read('static/js/movie-details-vue-bridge.js')
        show_details_bridge = self.read('static/js/show-details-vue-bridge.js')
        self.assertIn('global.renderMovieDetailPage = render;', movie_details_bridge)
        self.assertNotIn('function renderMovieDetailPage(', ui)
        self.assertIn('renderCollectionsIndexPage', ui)
        self.assertIn('renderCollectionDetailPage', ui)
        self.assertIn('renderMovieCrewTabHTML', ui)
        self.assertIn('function renderMovieDirectedByHTML(movie)', ui)
        self.assertNotIn('function renderSearchResults(', ui)
        self.assertIn('renderDiscoverGenreSection', ui)
        self.assertNotIn('function renderSearchTabButtonHTML(', ui)
        self.assertNotIn('function renderSearchResultPosterCard(', ui)
        self.assertNotIn('function renderSearchPersonCard(', ui)
        self.assertNotIn('function renderInactiveEyeFilterControlHTML(', ui)
        self.assertNotIn('function renderTrackerPersonSkeletonCards(', ui)
        self.assertIn('function lockSearchRouteBeforeResultOpen', ui)
        search_bridge = self.read('static/js/search-state-bridge.js')
        search_vue = self.read('frontend/src/search-discover/SearchResults.vue')
        self.assertIn('global.renderSearchResults = render;', search_bridge)
        self.assertIn('global.lockSearchRouteBeforeResultOpen', search_bridge)
        self.assertIn('global.getEyeFilteredRenderItems', search_bridge)
        self.assertIn('data-tvtracker-search-owner="vue"', search_vue)
        self.assertIn('data-person-role="person"', search_vue)
        self.assertIn('function buildCrew(show)', show_details_bridge)
        self.assertIn('global.normalizeThemeItems(show)', show_details_bridge)

    def test_friendly_error_page_copy_exists(self):
        routing = self.read('tvtracker/web/routing.py')
        error_template = self.read('templates/error.html')
        self.assertIn("Are you lost?", routing)
        self.assertNotIn("We're not in Kansas anymore", routing)
        self.assertIn('Houston, we have a problem', routing)
        self.assertIn('Something went wrong. Try again in a moment.', routing)
        self.assertIn('{{ error_title }}', error_template)
        self.assertIn('{{ error_text }}', error_template)
        self.assertIn('BACK TO APP', error_template)

    def test_phase55_navigation_loading_and_404_polish_exists(self):
        app_js = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')
        css = self.read('static/css/tailwind-input.css')
        error_template = self.read('templates/error.html')
        self.assertIn('navigateBackOrRouteFallback', app_js)
        self.assertIn('getNavigationFallbackRoute', app_js)
        self.assertIn('renderTrackerDetailSkeletonHTML', ui)
        self.assertIn('renderTrackerEpisodeSkeletonHTML', ui)
        self.assertIn('renderTrackerPosterSkeletonCards', ui)
        self.assertIn('tt-detail-skeleton', css)
        self.assertIn('tt-episode-skeleton', css)
        self.assertIn('route-error-hero', css)
        self.assertIn('route-error-gradient-1', css)
        self.assertIn('{{ route_error_gradient_class }}', error_template)
        self.assertNotIn("assets/images/404.png", error_template)


    def test_phase551_loading_back_and_404_correction_exists(self):
        app_js = self.read('static/js/app.js')
        router = self.read('static/js/app-router.js')
        css = self.read('static/css/tailwind-input.css')
        error_template = self.read('templates/error.html')
        self.assertIn('navigateBackToStoredRouteOrFallback', app_js)
        self.assertIn('pushDetailBackRoute', app_js)
        self.assertIn('cancelActiveSearchRequest();', app_js)
        self.assertIn('handleAppRouteAnchorClick', router)
        self.assertIn('document.addEventListener("click",handleAppRouteAnchorClick)', router)
        self.assertIn('route-error-gradient-1', css)
        self.assertIn('route-error-gradient-8', css)
        tailwind_config = self.read('tailwind.config.js')
        self.assertIn("'route-error-gradient-1'", tailwind_config)
        self.assertIn("'route-error-gradient-8'", tailwind_config)
        self.assertIn('getRouteErrorGradientClass', app_js)
        self.assertNotIn("background-image:url('/static/assets/images/404.png')", css)
        self.assertNotIn('rgba(0,0,0,.72);\n        padding:34px', css)
        self.assertIn('justify-content:flex-end', css)
        self.assertIn('{{ route_error_gradient_class }}', error_template)
        self.assertNotIn("assets/images/404.png", error_template)
        self.assertNotIn('tw-bg-black/70', error_template)
        self.assertNotIn('tw-backdrop-blur-sm', error_template)
        self.assertIn('Are you lost?', app_js)
        self.assertNotIn("We're not in Kansas anymore", app_js)
        self.assertIn('tw-py-[30px] tw-pl-[30px] tw-pr-0', css)
        self.assertIn('class="view-more-button route-error-app-button"', error_template)

    def test_auth_tabs_and_server_side_return_path_exist(self):
        routes = self.read('tvtracker/web/routes.py')
        auth_security = self.read('tvtracker/auth/security.py')
        login_template = self.read('templates/login.html')
        db_js = self.read('static/js/db.js')
        self.assertIn('post_login_path', auth_security)
        self.assertIn('@app.get("/signup")', routes)
        self.assertIn('Track your Movies, Shows and Anime all in one place', login_template)
        self.assertIn('Registration coming soon', login_template)
        self.assertNotIn('Your watch history stays private to this signed-in session.', login_template)
        self.assertNotIn('New account creation is not available yet.', login_template)
        self.assertIn('data-auth-tab="login"', login_template)
        self.assertIn('data-auth-tab="signup"', login_template)
        self.assertNotIn('name="next"', login_template)
        self.assertNotIn('login?next=', db_js)

    def test_app_uses_server_tmdb_proxy_without_browser_key_ui(self):
        config = self.read('static/js/config.js')
        tmdb = self.read('static/js/tmdb.js')
        ui = self.read('static/js/ui.js')
        template = self.read('templates/index.html')
        self.assertIn('const TMDB_API_BASE = "/api/tmdb"', config)
        self.assertIn('The key is held by Flask', tmdb)
        self.assertNotIn('TMDB API KEY', ui)
        self.assertNotIn('TVTrackerStaticAdapter', ui)
        self.assertNotIn('static-adapter.js', template)

    def test_frontend_security_hardening_exists(self):
        routes = self.read('tvtracker/web/routes.py')
        ui = self.read('static/js/ui.js')
        self.assertIn('function safeExternalURL', ui)
        self.assertIn('const homepageURL = show ? safeExternalURL(show.homepage) : "";', ui)
        self.assertNotIn('href="${escapeHTML(show.homepage)}"', ui)
        self.assertIn('"script-src \'self\'"', routes)
        self.assertIn('"style-src \'self\' \'unsafe-inline\'"', routes)
        self.assertNotIn('cdn.jsdelivr.net', routes)

    def test_profile_header_presets_survive_tailwind_purge(self):
        config = self.read('tailwind.config.js')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')
        profile_settings = self.read('frontend/src/settings/SettingsProfile.vue')
        self.assertIn('profile-header-${preset[0]}', profile_settings)
        for class_name in (
            'profile-header-default',
            'profile-header-blue',
            'profile-header-purple',
            'profile-header-green',
            'profile-header-amber',
            'profile-header-monochrome',
        ):
            self.assertIn(class_name, config)
            self.assertIn(f'.{class_name}', source_css)
            self.assertIn(f'.{class_name}', built_css)

    def test_app_asset_paths_are_refresh_safe(self):
        app_js = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')
        self.assertNotIn('src="static/assets/', app_js)
        self.assertNotIn('src="static/assets/', ui)
        self.assertIn('src="/static/assets/icons/arrow-narrow-left.svg"', app_js)
        self.assertIn('src="/static/assets/icons/arrow-narrow-left.svg"', ui)


    def test_phase_66j_adult_badge_and_collection_search_exist(self):
        app_js = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')
        router = self.read('static/js/app-router.js')
        app_py = self.read('app.py')
        css = self.read('static/css/tailwind-input.css')
        search_vue = self.read('frontend/src/search-discover/SearchResults.vue')
        self.assertIn('"collection"', app_js)
        self.assertIn('search/collection', app_js)
        self.assertIn('tmdbSearchCollectionsPage', app_js)
        self.assertIn('data-collection-search', ui)
        self.assertIn('renderMovieTitleWithAdultBadgeHTML', ui)
        self.assertIn('adult-movie-badge', css)
        self.assertIn('adult-movie-badge', search_vue)
        self.assertIn('"person","collection"', app_js)
        routing = self.read('tvtracker/web/routing.py')
        self.assertIn('"person", "collection"', routing)
        self.assertIn('rawQuery', router)
        self.assertIn('eye-filter-menu-inactive search-eye-filter-menu', search_vue)
        self.assertIn('runCollectionsLiveFallbackSearch', app_js)
        self.assertIn('tmdbSearchCollectionsPage(cleanQuery,1)', app_js)
        self.assertIn('collection-search-card', search_vue)
        self.assertIn('movie-title-with-adult-badge', css)

    def test_deploy_workflow_tests_and_checks_healthz(self):
        routes = self.read('tvtracker/web/routes.py')
        workflow = self.read('.github/workflows/deploy.yml')
        readme = self.read('README.md')
        run_all = self.read('tests/run_all.py')

        self.assertIn('@app.get("/healthz")', routes)
        self.assertIn('@app.get("/api/health")', routes)
        self.assertIn('python tests/run_all.py', workflow)
        self.assertIn('appleboy/ssh-action@7eaf76671a0d7eec5d98ee897acda4f968735a17', workflow)
        self.assertIn('actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1', workflow)
        self.assertIn('actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548', workflow)
        self.assertIn('actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38', workflow)
        self.assertIn('workflow_dispatch:', workflow)
        self.assertIn('group: tv-tracker-production', workflow)
        self.assertIn('cancel-in-progress: false', workflow)
        self.assertIn("if: github.ref == 'refs/heads/main'", workflow)
        self.assertIn('ref: ${{ github.sha }}', workflow)
        self.assertIn('APP_DIR_B64:', workflow)
        self.assertIn('envs: APP_DIR_B64,DEPLOY_SHA', workflow)
        self.assertNotIn('cd "${{ secrets.ALWAYSDATA_APP_DIR }}"', workflow)
        self.assertGreaterEqual(
            workflow.count('git -C "$APP_DIR" fetch --no-tags origin refs/heads/main'),
            2,
        )
        migration_index = workflow.index('"$PYTHON_BIN" -m tvtracker.migrations')
        activation_index = workflow.index(
            'git -C "$APP_DIR" checkout --detach "$DEPLOY_SHA"'
        )
        self.assertLess(migration_index, activation_index)
        self.assertIn('.tvtracker-release-sha', workflow)
        self.assertIn('payload.get("releaseSha")', workflow)
        self.assertIn('releaseSha', routes)
        self.assertNotIn('git pull', workflow)
        self.assertIn('ALWAYSDATA_HEALTH_URL', workflow)
        self.assertIn('ALWAYSDATA_APP_DIR', workflow)
        self.assertNotIn('example-account', workflow)
        self.assertNotIn('ssh-example-account', workflow)
        self.assertIn('/healthz', readme)
        self.assertIn('.glob("test_*.js")', run_all)

    def test_phase51_search_routing_polish_exists(self):
        app_js = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')
        router = self.read('static/js/app-router.js')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')
        search_vue = self.read('frontend/src/search-discover/SearchResults.vue')

        self.assertIn('const SEARCH_RESULT_BATCH_SIZE = 21', app_js)
        self.assertIn('function tmdbSearchMediaPage', app_js)
        self.assertIn('search/tv', app_js)
        self.assertIn('search/movie', app_js)
        self.assertIn('search/person', app_js)
        self.assertIn('replaceState({tvTrackerRoute:true}', router)
        self.assertIn('getSearchRoute(query="",media="tv")', app_js)
        self.assertIn('&type=${encodeURIComponent(cleanMedia)}', app_js)
        self.assertIn('currentSearchMediaType', router)
        self.assertIn('Start typing to search.', search_vue)
        self.assertNotIn('Browse TV shows, movies, and genres.', ui)
        self.assertNotIn('Results for ${escapeHTML(query)}', ui)
        self.assertNotIn('known_for_department ? String(result.known_for_department)', ui)
        self.assertIn('search-person-skeleton-card', search_vue)
        self.assertIn('search-person-skeleton-card', source_css)
        self.assertIn('search-person-skeleton-card', built_css)

    def test_phase52_route_restore_shells_use_explicit_context(self):
        app_js = self.read('static/js/app.js')

        self.assertIn('function getDiscoveryNavContext(options={},route="")', app_js)
        self.assertIn('function showGenreDetailPageShell(navigationContext="")', app_js)
        self.assertIn('function showDiscoveryFilterPageShell(navigationContext="")', app_js)
        self.assertIn('showGenreDetailPageShell(navigationContext)', app_js)
        self.assertIn('showDiscoveryFilterPageShell(navigationContext)', app_js)
        self.assertIn('rememberRouteNavContext(genreRoute,navigationContext)', app_js)
        self.assertIn('rememberRouteNavContext(initialDiscoveryRoute,navigationContext)', app_js)
        self.assertIn('return "discover";', app_js)
        self.assertNotIn('function showGenreDetailPageShell(){', app_js)
        self.assertNotIn('function showDiscoveryFilterPageShell(){', app_js)

    def test_phase53_genre_media_upgrade_exists(self):
        app_py = self.read('app.py')
        app_js = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')
        router = self.read('static/js/app-router.js')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')

        self.assertNotIn('APP_LEGACY_GENRE_PATH_RE', app_py)
        self.assertNotIn('legacy_genre_redirect_path', app_py)
        self.assertIn('APP_GENRE_PATH_RE', app_py)
        self.assertIn('const GENRE_MEDIA_TYPES = new Set(["tv","movie"])', app_js)
        self.assertNotIn('function getLegacyGenreRouteInfo', app_js)
        self.assertIn('function getGenreMediaSwitchRoute', app_js)
        self.assertIn('tmdbGetMovieGenreList', app_js)
        self.assertIn('tmdbGetDiscoverPage("discover/" + media', app_js)
        browse_js = self.read('static/js/discover-browse.js')
        self.assertIn('primary_release_year', browse_js)
        self.assertIn('openGenrePage(params.key || params.id,{fromRoute:true,media:params.media,browseState:params.browseState,routeSlug:params.slug})', router)
        self.assertNotIn('getLegacyGenreRouteInfo', router)
        self.assertIn('discover-genre-tab', ui)
        self.assertIn('genre-media-switch-button', ui)
        self.assertIn('getGenreDetailRoute(genre.id,name,media)', ui)
        self.assertIn('renderShowGenreLinksHTML(genres,"movie")', ui)
        self.assert_css_rule_has(source_css, '.discover-genre-tab', '@apply tw-inline-flex')
        self.assert_css_rule_has(built_css, '.discover-genre-tab', 'display:inline-flex')

    def test_phase6_movie_page_profile_and_navigation_repairs_exist(self):
        routes = self.read('tvtracker/web/routes.py')
        app_js = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')
        css = self.read('static/css/tailwind-input.css')
        template = self.read('templates/index.html')
        backup_validation = self.read('tvtracker/backup/validation.py')
        self.assertIn('favorite_movies', backup_validation)
        self.assertIn('app_valid_spa_fallback', routes)
        self.assertIn('@app.get("/app/<path:app_path>", strict_slashes=False)', routes)
        self.assertIn('favorite_movies', app_js)
        self.assertIn('normalizeFavoriteMovieRecord', app_js)
        self.assertIn('addFavoriteMovie', app_js)
        self.assertIn('Movie Name', 'Movie Name')
        self.assertIn('FAVORITE MOVIES', ui)
        self.assertIn('renderFavoriteMoviesPopup', ui)
        self.assertIn('renderMovieTabsHTML', ui)
        self.assertIn('Info","Cast","Crew","Details","Genres","Releases', ui)
        self.assertIn('movie-page-status-button', ui)
        self.assertIn('renderMovieCrewTabHTML', ui)
        self.assertIn('function renderMovieDirectedByHTML(movie)', ui)
        self.assertIn('renderMovieReleasesHTML', ui)
        self.assertIn('lockSearchRouteBeforeResultOpen', ui)
        self.assertIn('favorites-popup-title', template)
        self.assertIn('movie-page-actions-wrap', css)

    def test_phase601_movie_layout_search_state_and_person_roles_exist(self):
        app_js = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')
        css = self.read('static/css/tailwind-input.css')
        error_template = self.read('templates/error.html')
        movie_details_component = self.read('frontend/src/media-details/MovieDetails.vue')
        self.assertIn('movie-page-hero-shell', movie_details_component)
        self.assertIn('movie-page-identity-row', movie_details_component)
        self.assertIn('modal-hero show-detail-hero show-page-hero movie-page-hero', movie_details_component)
        self.assertIn('pushExplicitDetailBackRoute', app_js)
        self.assertIn('backRoute:backRoute', ui)
        self.assertIn('getPersonCreditRoleLabel', app_js)
        self.assertIn('person_role_label', app_js)
        self.assertIn('Actor: ', app_js)
        self.assertIn('width:min(640px,48vw)', css)
        self.assertIn('class="route-error-copy"', error_template)

    def test_phase602_movie_info_cleanup_exists(self):
        ui = self.read('static/js/ui.js')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')
        info_start = ui.index('function renderMovieInfoTabHTML(movie)')
        info_end = ui.index('function renderMovieActiveTabContentHTML(movie)')
        info_block = ui[info_start:info_end]
        details_start = ui.index('function renderMovieDetailsTabHTML(movie)')
        details_end = ui.index('function renderMovieInfoTabHTML(movie)')
        details_block = ui[details_start:details_end]

        self.assertIn('function renderMovieCompanyLogosHTML', ui)
        self.assertIn('movie-info-tagline', info_block)
        self.assertIn('movie.overview || "Unknown"', info_block)
        self.assertNotIn('renderMovieGenresHTML(movie)', info_block)
        self.assertNotIn('renderMovieProvidersHTML(movie)', info_block)
        self.assertNotIn('Directed by', info_block)
        self.assertNotIn('Written by', info_block)
        self.assertNotIn('Budget', details_block)
        self.assertNotIn('Revenue', details_block)
        self.assertIn('if(productionCompaniesHTML)', details_block)
        self.assertIn('renderMovieCompanyLogosHTML(movie && movie.production_companies)', details_block)
        self.assertIn('movie-company-logo', source_css)
        self.assertIn('movie-company-logo', built_css)

    def test_phase603_details_consistency_and_releases_exist(self):
        ui = self.read('static/js/ui.js')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')
        detail_block = self.read('static/js/movie-details-vue-bridge.js')
        crew_start = ui.index('function renderMovieCrewTabHTML(movie)')
        crew_block = ui[crew_start:ui.index('function renderMovieDetailsTabHTML(movie)', crew_start)]
        release_start = ui.index('function renderMovieReleasesHTML(movie)')
        release_block = ui[release_start:ui.index('function renderMovieCastTabHTML(movie)', release_start)]

        self.assertIn('fragment("renderMovieDirectedByHTML",movie)', detail_block)
        self.assertIn('callString("renderMovieGenresHTML",movie)', detail_block)
        self.assertNotIn('movie.tagline ? `<p class="show-detail-tagline">', detail_block)
        self.assertIn('font-style:italic;', source_css)
        self.assertIn('font-style:italic;', built_css)
        self.assertIn('renderCrewJobGroupsHTML(Array.isArray(movie && movie.crew) ? movie.crew : [],"movie","Unknown")', crew_block)
        self.assertIn('function renderCrewJobGroupsHTML(source,media="tv",emptyText="Unknown")', ui)
        self.assertIn('movie-crew-department-list', source_css)
        self.assertIn('movie-crew-department-list', built_css)
        self.assertIn('function renderCompanyLogoTilesHTML(companies,media="tv")', ui)
        self.assertIn('return renderCompanyLogoTilesHTML(companies,"tv") || "Unknown";', ui)
        self.assertIn('background:#f3f3f3;', source_css)
        self.assertIn('background:#f3f3f3;', built_css)
        self.assertIn('movie-release-country-list', release_block)
        self.assertIn('renderMovieReleaseCountryRowHTML', release_block)
        self.assertIn('movie-release-certification-badge', ui)
        self.assertIn('localeCompare(String(b.countryName', ui)
        self.assertIn('movie-release-country-row', source_css)
        self.assertIn('movie-release-country-row', built_css)

    def test_phase604_detail_polish_releases_and_placeholders_exist(self):
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')
        details_block = self.read('frontend/src/media-details/MovieDetails.vue')
        show_details_bridge = self.read('static/js/show-details-vue-bridge.js')
        self.assertIn('function buildDetails(show)', show_details_bridge)
        self.assertIn('function buildGenres(show)', show_details_bridge)
        ui = self.read('static/js/ui.js')
        releases_start = ui.index('function renderMovieReleaseSortControlHTML(sortMode)')
        releases_block = ui[releases_start:ui.index('function renderMovieCastTabHTML(movie)', releases_start)]

        self.assertIn('v-for="(node, index) in model.externalLinks"', details_block)
        self.assertIn('class="show-page-actions-wrap movie-page-actions-wrap"', details_block)
        self.assertIn('movie-release-country-list', releases_block)
        self.assertIn('renderMovieReleaseCountryRowHTML', releases_block)
        self.assertIn('movie-release-sort-note', releases_block)
        self.assertNotIn('groupedByType', releases_block)
        self.assertIn('person-silhouette-placeholder', source_css)
        self.assertIn('person-silhouette-placeholder', built_css)
        self.assertIn('show-genres-tab-stack', source_css)
        self.assertIn('show-genres-tab-stack', built_css)
        self.assertIn('movie-release-country-list', source_css)
        self.assertIn('movie-release-country-list', built_css)



    def test_phase605_small_detail_cleanup_exists(self):
        app = self.read('static/js/app.js')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')
        show_details_bridge = self.read('static/js/show-details-vue-bridge.js')
        genres_start = show_details_bridge.index('function buildGenres(show)')
        themes_block = show_details_bridge[genres_start:show_details_bridge.index('function providerWatchLink', genres_start)]
        ui = self.read('static/js/ui.js')
        releases_start = ui.index('function renderMovieReleaseSortControlHTML(sortMode)')
        releases_block = ui[releases_start:ui.index('function renderMovieCastTabHTML(movie)', releases_start)]

        self.assertIn('show-detail-theme-list-expanded', themes_block)
        self.assertNotIn('data-show-themes-more', themes_block)
        self.assertNotIn('...more', themes_block)
        self.assertIn('var activeMovieReleaseSort = "date";', app)
        self.assertIn('activeMovieReleaseSort = "date";', app)
        self.assertIn('data-movie-release-sort-toggle', ui)
        self.assertIn('data-movie-release-sort-toggle', app)
        self.assertIn('renderMovieReleaseSortControlHTML(sortMode)', releases_block)
        self.assertIn('groupMovieReleasesByDate(releases)', releases_block)
        self.assertIn('groupMovieReleasesByCountry(releases)', ui)
        self.assertIn('movie-release-date-row', releases_block)
        self.assertIn('movie-release-date-entry-list', releases_block)
        self.assertIn('movie-release-date-row', source_css)
        self.assertIn('movie-release-date-row', built_css)
        self.assertIn('movie-release-sort-button', source_css)
        self.assertIn('movie-release-sort-button', built_css)


    def test_phase606_release_dropdown_and_visual_polish_exists(self):
        ui = self.read('static/js/ui.js')
        app = self.read('static/js/app.js')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')
        releases_start = ui.index('function renderMovieReleaseSortControlHTML(sortMode)')
        releases_block = ui[releases_start:ui.index('function renderMovieReleaseEntryHTML(release)', releases_start)]

        self.assertIn('data-movie-release-sort-menu', releases_block)
        self.assertIn('data-movie-release-sort-option', releases_block)
        self.assertIn('movie-release-sort-current', releases_block)
        self.assertIn('movie-release-sort-menu-wrap', source_css)
        self.assertIn('movie-release-sort-menu-wrap', built_css)
        self.assertIn('movie-release-sort-menu-option', source_css)
        self.assertIn('movie-release-sort-menu-option', built_css)
        self.assertIn('closeMovieReleaseSortMenus', app)
        self.assertIn('tvTrackerMovieReleaseSortOutsideBound', app)
        for css in (source_css, built_css):
            self.assert_css_rule_has(
                css,
                '.movie-release-country-row',
                'border:0',
                'border-bottom:1px solid rgba(255,255,255,.12)',
            )
        self.assertIn('font:inherit;', source_css)
        self.assertIn('font:inherit;', built_css)
        self.assertIn('margin-top:22px;', source_css)
        self.assertIn('margin-top:22px;', built_css)


    def test_movie_genres_people_media_and_discover_gradients_exist(self):
        ui = self.read('static/js/ui.js')
        app = self.read('static/js/app.js')
        router = self.read('static/js/app-router.js')
        backend = self.read('app.py')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')
        self.assertIn('function renderMovieGenresTabHTML(movie)', ui)
        self.assertIn('renderMovieThemesDetailsHTML(movie)', ui)
        self.assertIn('data-discovery-media="${escapeHTML(cleanMedia)}"', ui)
        self.assertIn('["Info","Cast","Crew","Details","Genres","Releases"]', ui)
        self.assertNotIn('id="person-media-filter"', ui)
        self.assertIn('data-person-media="tv"', ui)
        self.assertIn('data-person-media="movie"', ui)
        self.assertIn('genre-media-switch-button', ui)
        self.assertNotIn('<div class="person-profile-name">', ui)
        self.assertIn('.v2-more-like-section{', source_css)
        self.assertIn('@apply tw-mt-7;', source_css)
        self.assertIn('.v2-more-like-section{margin-top:1.75rem}', built_css)
        self.assertIn('DISCOVER_GENRE_TONE_CLASSES', ui)
        self.assertIn('discover-genre-tone-horror', source_css)
        self.assertIn('discover-genre-tone-science-fiction', source_css)
        self.assertIn('discover-genre-tone-horror', built_css)
        self.assertIn('discover-genre-tone-science-fiction', built_css)
        self.assertIn('radial-gradient(circle at 12% 20%', source_css)
        self.assertIn('radial-gradient(circle at 12% 20%', built_css)
        self.assertIn('cleanType === "theme" ? requestedMedia', app)
        self.assertIn('typedDiscoveryIdMatch', router)
        self.assertIn('APP_THEME_PATH_RE', backend)
        self.assertNotIn('APP_MOVIE_THEME_PATH_RE', backend)

    def test_phase_63b_media_routes_and_country_filtering_exist(self):
        app = self.read('static/js/app.js')
        router = self.read('static/js/app-router.js')
        ui = self.read('static/js/ui.js')
        backend = self.read('app.py')

        self.assertIn('`/app/${encodeURIComponent(cleanType)}/${encodeURIComponent(cleanMedia)}/${encodeURIComponent(key)}`', app)
        self.assertIn('`/app/year/${encodeURIComponent(cleanMedia)}/${encodeURIComponent(clean)}`', app)
        self.assertIn('return `${getLanguageName(cleanValue)} ${mediaWord}`;', app)
        self.assertIn('cleanType === "language" || cleanType === "country" || cleanType === "company" || cleanType === "provider" || cleanType === "year"', app)
        self.assertIn('normalizeBrowseMediaType(discoveryPageState && discoveryPageState.media) === media', app)
        browse = self.read('static/js/discover-browse.js')
        self.assertIn('params.with_origin_country = state.country.toUpperCase();', browse)
        self.assertNotIn('params.region =', browse)
        self.assertIn('if(cleanMedia === "movie"){', app)
        self.assertIn('media:params.media || "tv"', router)
        self.assertIn('String(personSearchParams.get("media") || "")', router)
        self.assertIn(r'/app\/language\/(tv|movie)', router)
        self.assertIn(r'/app\/country\/(tv|movie)', router)
        self.assertIn(r'/app\/year\/(tv|movie)', router)
        self.assertIn('data-discovery-media="${escapeHTML(media)}"', ui)
        self.assertIn('language.code === originalLanguage', ui)
        self.assertIn('getPersonDetailRoute(movieRole,pageState.personId,personRouteLabel,"movie",pageState)', ui)
        routing = self.read('tvtracker/web/routing.py')
        self.assertIn('APP_LANGUAGE_PATH_RE = re.compile(r"^/app/language/(tv|movie)/', routing)
        self.assertIn('APP_THEME_PATH_RE = re.compile(rf"^/app/theme/(tv|movie)/', routing)
        self.assertIn('if media_type == "movie":', routing)
        self.assertIn('params["media"] = "movie"', routing)
        self.assertIn('if role:', routing)
        self.assertIn('params["role"] = role', routing)

    def test_phase_63c_unified_discover_browse_exists(self):
        app = self.read('static/js/app.js')
        browse = self.read('static/js/discover-browse.js')
        router = self.read('static/js/app-router.js')
        ui = self.read('static/js/ui.js')
        backend = self.read('app.py')
        template = self.read('templates/index.html')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')

        self.assertIn('discover-browse.js', template)
        self.assertIn('BROWSE BY', ui)
        self.assertIn('function renderBrowseChevronIcon', ui)
        self.assertIn('function getBrowseYearControlLabel', ui)
        self.assertIn('getBrowseYearControlLabel(state)', ui)
        self.assertIn('state.decade', ui)
        self.assertIn('normalizeDecade', browse)
        self.assertIn('params["first_air_date.gte"] = startDate;', browse)
        self.assertIn('params["primary_release_date.gte"] = startDate;', browse)
        self.assertIn('GENRE ${renderBrowseChevronIcon()}', ui)
        self.assertIn('COUNTRY ${renderBrowseChevronIcon()}', ui)
        self.assertIn('LANGUAGE ${renderBrowseChevronIcon()}', ui)
        self.assertIn('OTHER ${renderBrowseChevronIcon()}', ui)
        self.assertIn('SORT ${renderBrowseChevronIcon()}', ui)
        self.assertNotIn('SORT ${sortSummary', ui)
        self.assertNotIn('SERVICE <span', ui)
        self.assertIn('Search themes', ui)
        self.assertIn('Search production companies', ui)
        self.assertIn('Search networks', ui)
        self.assertIn('US Certification', ui)
        self.assertIn('Production Company', ui)
        self.assertIn('function renderBrowseCheckIcon', ui)
        self.assertNotIn('browse-selected-heading', ui)
        self.assertIn('data-browse-set-single="network"', ui)
        self.assertIn('Returning Series', ui)
        self.assertIn('browse-active-chip', ui)
        self.assertIn('CLEAR ALL', ui)
        self.assertIn('Popularity — High to Low', ui)
        self.assertNotIn('["title-desc","Title — Z to A"]', ui)
        self.assertIn('const currentYear = new Date().getFullYear();', ui)
        self.assertIn('function renderBrowseDecadeYearsHTML', ui)
        self.assertIn('function renderBrowseDecadeListHTML', ui)
        self.assertIn('data-browse-year-open-decade=', ui)
        self.assertIn('data-browse-year-show-decades', ui)
        self.assertIn('data-browse-year-shift=', ui)
        self.assertIn('data-browse-decade-years', ui)
        self.assertIn('data-browse-option-search=', ui)
        self.assertIn('uk great britain britain', ui)
        self.assertNotIn('Genre ${id}', ui)
        self.assertNotIn('Theme ${id}', ui)
        self.assertNotIn('Company ${id}', ui)
        self.assertNotIn('<section class="discover-browse-panel" aria-label="Browse TV shows and movies">', ui)

        self.assertIn('MULTI_KEYS', browse)
        self.assertIn('state.genres.join("|")', browse)
        self.assertIn('state.themes.join("|")', browse)
        self.assertIn('state.companies.join("|")', browse)
        self.assertIn('params.with_origin_country = state.country.toUpperCase();', browse)
        self.assertIn('params.with_original_language = state.language;', browse)
        self.assertIn('params["vote_count.gte"] = media === "movie" ? 50 : 20;', browse)
        self.assertIn('params.certification_country = "US";', browse)
        routing_63c = self.read('tvtracker/web/routing.py')
        self.assertIn('APP_CERTIFICATION_PATH_RE = re.compile(r"^/app/certification/movie/', routing_63c)
        self.assertIn('if(media !== "movie")', ui)
        self.assertIn('params["first_air_date.gte"] = today;', browse)
        self.assertIn('return "/app/browse/"', browse)

        self.assertIn('browseMatch', router)
        self.assertIn('openBrowsePage', router)
        self.assertIn('browseState:params.browseState', router)
        self.assertIn('APP_BROWSE_PATH_RE', backend)
        routes_63c = self.read('tvtracker/web/routes.py')
        self.assertIn('@app.get("/api/tmdb/network-search")', routes_63c)
        tmdb_exports = self.read('tvtracker/media/tmdb_exports.py')
        self.assertIn('tv_network_ids_', tmdb_exports)
        self.assertIn('TMDB_NETWORK_EXPORT_CACHE_TTL_SECONDS', tmdb_exports)
        self.assertIn('normalize_tmdb_network_search_text', tmdb_exports)
        routing = self.read('tvtracker/web/routing.py')
        self.assertIn('canonical_browse_query', routing)
        self.assertIn('@app.get("/app/browse/<media_type>", strict_slashes=False)', routes_63c)
        self.assertIn('function navigateToBrowseState', app)
        self.assertIn('function mapBrowseGenresForMedia', app)
        self.assertIn('search/keyword', app)
        self.assertIn('search/company', app)
        self.assertNotIn('search/network', app)
        self.assertIn('/api/tmdb/network-search?q=', app)
        self.assertIn('function ensureBrowseGlobalInteractionEvents', app)
        self.assertIn('document.addEventListener("pointerdown"', app)
        self.assertIn('event.key === "Escape"', app)
        self.assertIn('Searching…', app)
        self.assertIn('browsePickerSearchRequestId', app)
        self.assertNotIn('seenNames', app)
        self.assertIn('seenIds.has(id)', app)
        self.assertIn('function shiftBrowseYearDecade', app)
        self.assertIn('function resetBrowseYearDropdown', app)
        self.assertIn('function buildDiscoverCategoryBrowseRequest', app)
        self.assertIn('function sortBrowseResultsForDisplay', app)
        self.assertNotIn('title-asc', browse)
        self.assertNotIn('title-desc', browse)
        self.assertIn('.browse-bar{', source_css)
        self.assertIn('.browse-active-chip', source_css)
        self.assertIn('.browse-chevron', source_css)
        self.assertIn('.browse-year-strip{', source_css)
        self.assertIn('.browse-selected-check', source_css)
        self.assertIn('.browse-dropdown-option[hidden]', source_css)
        self.assertIn('.browse-bar{', built_css)
        self.assertIn('.browse-active-chip', built_css)
        self.assertIn('.browse-chevron', built_css)
        self.assertIn('.browse-dropdown-option[hidden]', built_css)

    def test_phase_65a_eye_filters_and_person_progress_exist(self):
        app = self.read('static/js/app.js')
        browse = self.read('static/js/discover-browse.js')
        router = self.read('static/js/app-router.js')
        ui = self.read('static/js/ui.js')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')

        self.assertIn('fadeWatched:false', app)
        self.assertIn('hideWatched:false', app)
        self.assertIn('hidePlan:false', app)
        self.assertIn('hideFavorites:false', app)
        self.assertIn('function handleEyeFilterToggle', app)
        self.assertIn('function applyEyeFiltersToItems', app)
        self.assertIn('function getPersonProgressSummary', app)
        self.assertIn('function isTrackedTVShowWatched', app)
        self.assertIn('state.hideWatched || state.hidePlan || state.hideFavorites', browse)
        self.assertIn('fadeWatched=1', browse)
        self.assertIn('hideFavorites=1', router)
        self.assertIn('canonicalEyeParams', router)
        self.assertIn('eyeState:searchState.eyeState', router)
        self.assertIn('eyeState:personEye.eye', router)
        self.assertIn('data-eye-filter-summary', ui)
        self.assertIn('data-eye-toggle="${escapeHTML(key)}"', ui)
        self.assertIn('Hide Plan to Watch', ui)
        self.assertIn('renderPersonProgressCardHTML', ui)
        self.assertIn("<span>You've watched</span>", ui)
        self.assertIn('${escapeHTML(String(watched))} of ${escapeHTML(String(total))}', ui)
        self.assertLess(ui.index('browse-menu-sort'), ui.index('browse-eye-filter-menu'))
        self.assertIn('<strong>${escapeHTML(String(percent))}</strong><span>%</span>', ui)
        self.assertIn('eye-open.png', ui)
        self.assertIn('eye-closed.png', ui)
        self.assertIn('.eye-filter-button', source_css)
        self.assertIn('.eye-filter-faded', source_css)
        self.assertIn('.person-progress-card', source_css)
        self.assertIn('.person-progress-percent', source_css)
        self.assertIn('.eye-filter-button', built_css)
        self.assertIn('.person-progress-card', built_css)
        self.assertIn('.person-progress-percent', built_css)

    def test_phase65b_more_link_and_release_sort_visual_polish_exists(self):
        ui = self.read('static/js/ui.js')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')
        releases_start = ui.index('function renderMovieReleaseSortControlHTML(sortMode)')
        releases_block = ui[releases_start:ui.index('function sortMovieReleaseRows', releases_start)]
        self.assertIn('renderBrowseChevronIcon("movie-release-sort-chevron-icon")', releases_block)
        self.assertNotIn('>⌄</span>', releases_block)
        self.assert_css_rule_has(
            source_css,
            '.person-bio-more-button',
            'color:rgba(255,255,255,.68)',
        )
        self.assertIn('background:#202124;', source_css)
        self.assertIn('background:#323438;', source_css)
        self.assertIn('movie-release-sort-chevron-icon', built_css)
        self.assert_css_rule_has(
            built_css,
            '.person-bio-more-button',
            'color:rgba(255,255,255,.68)',
        )

    def test_main_list_initial_skeleton_and_hidden_soap_genre_exist(self):
        ui = self.read('static/js/ui.js')
        router = self.read('static/js/app-router.js')
        template = self.read('templates/index.html')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')

        self.assertNotIn("initial_app_path.startswith('/app/list/')", template)
        self.assertIn('{% for _ in range(5) %}', template)
        self.assertIn('watchlist-skeleton-row', template)
        self.assertIn('function configureInitialListSkeleton(filter)', router)
        self.assertIn('hideAction = String(filter || "watching") === "finished"', router)
        self.assertIn('watchlist-skeleton-shimmer 1.4s infinite', source_css)
        self.assertIn('rgba(255,255,255,.055)', source_css)
        self.assertIn('@media (prefers-reduced-motion:reduce)', source_css)
        self.assertIn('watchlist-skeleton-shimmer 1.4s infinite', built_css)
        self.assertIn('cleanMedia === "tv" && name.toLowerCase() === "soap"', ui)

    def test_global_real_links_and_movie_favorite_sync_exist(self):
        template = self.read('templates/index.html')
        ui = self.read('static/js/ui.js')
        app = self.read('static/js/app.js')
        router = self.read('static/js/app-router.js')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')
        search_vue = self.read('frontend/src/search-discover/SearchResults.vue')

        self.assertIn('href="/app/list/watching"', template)
        self.assertIn('href="/app/discover"', template)
        self.assertIn('href="/app/profile"', template)
        self.assertIn('href="/app/settings"', template)
        self.assertIn('href="/app/upcoming"', template)
        self.assertIn('href="/app/history"', template)
        self.assertIn('class="watchlist-card-link"', self.read('frontend/src/tracker-lists/TrackerListsSurface.vue'))
        self.assertIn('class="app-route-card-link" href=', ui)
        self.assertIn('class="genre-result-card search-result-poster-card"', search_vue)
        self.assertIn('class="search-person-card"', search_vue)
        self.assertIn('class="genre-result-card person-result-card"', ui)
        self.assertIn('class="profile-favorite-slot filled" href=', ui)
        self.assertIn('class="v2-actor-list-row v2-person-card-link" href=', ui)
        self.assertIn('data-browse-media="tv"', ui)
        self.assertIn('event.metaKey', router)
        self.assertIn('event.ctrlKey', router)
        self.assertIn('event.shiftKey', router)
        self.assertIn("event.target.closest('a[href]')", router)
        self.assertIn('watchlist-card-link', source_css)
        self.assertIn('watchlist-card-link', built_css)
        self.assertIn('app-route-card-link', source_css)
        self.assertIn('app-route-card-link', built_css)

        self.assertIn('function isMovieFavorite(movieId)', app)
        self.assertIn('async function setMovieFavoriteState(movie,shouldFavorite,options={})', app)
        self.assertIn('favorite:typeof isMovieFavorite === "function" ? isMovieFavorite(movieId)', app)
        self.assertIn('setMovieFavoriteState(base,!currentState.favorite,{showMessage:true})', app)
        self.assertIn('return setMovieFavoriteState(movie,true,{showMessage:false});', app)
        self.assertIn('return setMovieFavoriteState(existing,false,{showMessage:false});', app)
        self.assertIn('showToast("You can only choose 8 favorite movies")', app)
        self.assertIn('saveData({stateKeys:["profile","movies"]})', app)

    def test_phase66b_collection_index_filters_and_sorting_exist(self):
        app = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')
        router = self.read('static/js/app-router.js')
        backend = self.read('app.py')

        self.assertIn('const COLLECTIONS_PAGE_SIZE = 64;', app)
        self.assertIn('function createCollectionsIndexState(input={})', app)
        self.assertIn('function buildCollectionsIndexState(collections,state)', app)
        self.assertIn('function applyCollectionsIndexState(nextState={},options={})', app)
        self.assertIn('average_popularity', app)
        self.assertIn('average_rating', app)
        self.assertIn('newest_release_year', app)
        self.assertIn('data-collection-filter="genre"', ui)
        self.assertIn('data-collection-filter="decade"', ui)
        self.assertIn('Collection Size', ui)
        self.assertIn('Most Popular', ui)
        self.assertIn('Least Popular', ui)
        self.assertIn('Highest Rated', ui)
        self.assertIn('Lowest Rated', ui)
        self.assertIn('data-collection-view-more', ui)
        self.assertNotIn('>PREVIOUS</button>', ui)
        self.assertNotIn('>NEXT</button>', ui)
        self.assertNotIn('collections-pagination-status', ui)
        self.assertIn('canonicalCollectionsSearch', router)
        routing_66b = self.read('tvtracker/web/routing.py')
        self.assertIn('COLLECTION_SORT_MODES', routing_66b)
        self.assertIn('APP_COLLECTION_SORT_MODES', routing_66b)


    def test_phase61_movie_tracking_foundation_exists(self):
        app = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')
        backend = self.read('app.py')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')

        self.assertIn('movies:{}', app)
        self.assertIn('ensureMovieTrackingData()', app)
        self.assertIn('async function updateMovieTracking(movie,action)', app)
        self.assertIn('stateKeys=["movies"]', app)
        self.assertIn('function isMovieHistoryEntry(entry,movieId="")', app)
        self.assertIn('function toggleFavoriteShow(showId)', app)
        self.assertIn('showAppConfirm({', app)
        self.assertIn('data-movie-tracking-action="${escapeHTML(action)}"', ui)
        self.assertIn('renderMovieTrackingButtonHTML(state,"watched","Watched")', ui)
        self.assertIn('renderMovieTrackingButtonHTML(state,"plan","Plan to Watch")', ui)
        self.assertIn('renderFavoriteHeartButtonHTML(state.favorite,`data-movie-tracking-action="favorite"`)', ui)
        show_details_bridge = self.read('static/js/show-details-vue-bridge.js')
        self.assertIn('"data-show-favorite-button":"true"', show_details_bridge)
        primitives = self.read('tvtracker/backup/primitives.py')
        backup_validation = self.read('tvtracker/backup/validation.py')
        tracker_history = self.read('tvtracker/tracker/history.py')
        self.assertIn('ALLOWED_STATE_KEYS = {', primitives)
        self.assertIn('"movies",', primitives)
        self.assertIn('def validate_movie_tracking_state(raw_value: Any)', backup_validation)
        self.assertIn('entry["media_type"] = "movie"', backup_validation)
        self.assertIn('movie-watched-', tracker_history)
        self.assert_css_rule_has(source_css, '.watchlist-skeleton-block', 'background:#0b0b0b')
        self.assert_css_rule_has(built_css, '.watchlist-skeleton-block', 'background:#0b0b0b')
        self.assertIn('font:inherit;', source_css)
        self.assertIn('font:inherit;', built_css)


    def test_browse_runtime_person_roles_release_restore_and_lazy_refresh_exist(self):
        app = self.read('static/js/app.js')
        router = self.read('static/js/app-router.js')
        ui = self.read('static/js/ui.js')
        tmdb = self.read('static/js/tmdb.js')
        browse = self.read('static/js/discover-browse.js')
        backend = self.read('app.py')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')
        show_details_bridge = self.read('static/js/show-details-vue-bridge.js')

        self.assertIn('const TMDB_SEARCH_CACHE_TTL = 1000 * 60 * 60;', tmdb)
        self.assertIn('const TMDB_PROVIDER_CATALOG_CACHE_TTL = 1000 * 60 * 60 * 24;', tmdb)
        self.assertIn('async function tmdbGetWatchProviderCatalog(media,watchRegion="US")', tmdb)
        self.assertIn('"watch/providers",', tmdb.split('const TMDB_SHOW_APPEND_TO_RESPONSE = [',1)[1].split('];',1)[0])
        self.assertNotIn('tmdbGetTitleWatchProviders', tmdb)

        self.assertIn('params.with_watch_providers = state.providers.join("|");', browse)
        self.assertIn('params.watch_region = String(options.watchRegion || "US").toUpperCase();', browse)
        self.assertIn('params.with_watch_monetization_types = "flatrate";', browse)
        self.assertIn('const RUNTIME_RANGES = Object.freeze({', browse)
        self.assertIn('params["with_runtime.gte"]', browse)
        self.assertIn('params["with_runtime.lte"]', browse)
        self.assertIn('<summary class="browse-bar-button">SERVICE ${renderBrowseChevronIcon()}</summary>', ui)
        self.assertIn('<summary class="browse-bar-button">RUNTIME ${renderBrowseChevronIcon()}</summary>', ui)

        self.assertNotIn('Where to Watch', ui)
        self.assertNotIn('No watch options available in your region.', ui)
        self.assertNotIn('Powered by JustWatch', ui)
        self.assertNotIn('VIEW WATCH OPTIONS', ui)
        self.assertNotIn('loadDetailWatchProviders', app)
        self.assertIn('function buildReleases(show)', show_details_bridge)
        self.assertIn('providerGroup("Streaming",providers.flatrate,providers)', show_details_bridge)
        self.assertIn('providerGroup("Rent",providers.rent,providers)', show_details_bridge)
        self.assertIn('providerGroup("Buy",providers.buy,providers)', show_details_bridge)

        self.assertIn('function renderFavoriteHeartButtonHTML(active,attributes="")', ui)
        self.assertIn('Add to favorites', ui)
        self.assertIn('Remove from favorites', ui)
        self.assertIn('favorite-heart-button', source_css)
        self.assertIn('favorite-heart-button', built_css)
        self.assertIn('v2-rail-button-icon', ui)

        self.assertIn('async function refreshOpenTrackedShowMetadata(showId)', app)
        self.assertIn('if(!show || !shouldRefreshShow(show)){ return false; }', app)
        self.assertIn('refreshOpenTrackedShowMetadata(id).catch(()=>{});', app)
        self.assertIn('const twelveHours = 12 * 60 * 60 * 1000;', app)

        routing_genre = self.read('tvtracker/web/routing.py')
        self.assertIn('APP_GENRE_PATH_RE = re.compile(rf"^/app/genre/(tv|movie)/({APP_ROUTE_ID_SLUG})$")', routing_genre)
        self.assertIn('openGenrePage(params.key || params.id', router)
        self.assertIn('function getGenreDetailRoute(genreId,label="",media="tv")', app)
        self.assertNotIn('APP_TV_GENRE_SLUGS', routing_genre)
        self.assertNotIn('APP_MOVIE_GENRE_SLUGS', routing_genre)

        self.assertIn('function getPersonAvailableRoles(person,media="tv")', app)
        self.assertIn('data-person-role-filter', ui)
        self.assertIn('person-role-browse-bar', source_css)
        self.assertIn('function renderCrewJobGroupsHTML(source,media="tv",emptyText="Unknown")', ui)
        self.assertIn('renderMovieMoreLikeThisHTML(movie)', ui)
        self.assertIn('data-movie-similar-open', ui)
        self.assertIn('function formatRuntimeDisplay(runtimeMinutes)', ui)
        self.assertIn('renderRuntimeDetailLinkHTML(movie.runtime,"movie")', ui)
        self.assertIn('global.getRuntimeBrowseRoute(runtime,"tv")', show_details_bridge)

        self.assertIn('browse-service-logo-tile', source_css)
        self.assertIn('browse-service-logo-tile', built_css)
        self.assertNotIn('watch-provider-logo-tile', source_css)
        self.assertNotIn('watch-provider-logo-tile', built_css)


    def test_phase66c_collection_detail_filters_and_eye_exist(self):
        app_js = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')
        router = self.read('static/js/app-router.js')

        self.assertIn('const COLLECTION_DETAIL_DEFAULT_SORT = "collection-order";', app_js)
        self.assertIn('function createCollectionDetailFilterState(input={})', app_js)
        self.assertIn('function buildCollectionDetailState(collection,movies,filters,labels={})', app_js)
        self.assertIn('function applyCollectionDetailFilterState(nextState={},options={})', app_js)
        self.assertIn('There are no movies in this collection released in ${filters.year}', app_js)
        self.assertIn('if(activePage === "collection-detail")', app_js)
        self.assertIn('renderEyeFilterControlHTML(filters,"collection-detail-eye-filter-menu")', ui)
        self.assertIn('data-collection-detail-set="genre"', ui)
        self.assertIn('data-collection-detail-set="language"', ui)
        self.assertIn('Release Date — Newest', ui)
        self.assertIn('Title — A to Z', ui)
        self.assertIn('function canonicalCollectionDetailSearch(search)', router)
        self.assertIn('filters:filters.state', router)

    def test_phase66d_tmdb_collection_export_cache_exists(self):
        routes = self.read('tvtracker/web/routes.py')
        tmdb_exports = self.read('tvtracker/media/tmdb_exports.py')
        app_js = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')

        self.assertIn('TMDB_COLLECTION_EXPORT_CACHE_TTL_SECONDS = 24 * 60 * 60', tmdb_exports)
        self.assertIn('TMDB_COLLECTION_INDEX_CACHE_FILE = "tmdb_collection_index.json"', tmdb_exports)
        self.assertIn('def fetch_tmdb_collection_export(export_date: date)', tmdb_exports)
        self.assertIn('collection_ids_{export_date:%m_%d_%Y}.json.gz', tmdb_exports)
        self.assertIn('def build_tmdb_collection_index_batch()', tmdb_exports)
        self.assertIn('@app.get("/api/tmdb/collections")', routes)
        self.assertIn('@app.get("/api/tmdb/collections/<int:collection_id>")', routes)
        self.assertIn('if collections:', routes)

        self.assertIn('const DISCOVER_COLLECTION_IDS = Object.freeze', app_js)
        self.assertIn('async function tmdbGetCollectionIndex(options={})', app_js)
        self.assertIn('fetch("/api/tmdb/collections",{credentials:"same-origin",cache:"no-store"}', app_js)
        self.assertIn('fetch("/api/tmdb/collections/" + encodeURIComponent(id)', app_js)
        self.assertIn('scheduleCollectionIndexPoll()', app_js)
        self.assertIn('async function loadCollectionIndexWithFallback(options={})', app_js)
        self.assertIn('function mergeCollectionLists(primary,secondary)', app_js)
        self.assertIn('mergeCollectionLists(indexedCollections,fallbackCollections)', app_js)
        self.assertIn('const fallbackCollections = await loadCuratedCollectionFallback({limit:DISCOVER_COLLECTION_ROW_LIMIT * 4});', app_js)
        self.assertIn('sortCollectionsForIndex(mergeCollectionLists(promotableIndexedCollections,fallbackCollections).filter(isPromotableCollection),"popularity.desc")', app_js)
        self.assertIn('payload.building === true', app_js)
        self.assertNotIn('Collections are loading. Please refresh in a moment.', ui)
        self.assertIn('No matching collections found.', ui)


    def test_phase66g_collection_and_global_title_placeholders_exist(self):
        tmdb_exports = self.read('tvtracker/media/tmdb_exports.py')
        app_js = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')

        self.assertIn('"poster_slots": poster_slots,', tmdb_exports)
        self.assertIn('def tmdb_collection_summary_has_poster_slots(summary: dict[str, Any]) -> bool:', tmdb_exports)
        self.assertIn('needs_poster_slot_backfill', tmdb_exports)
        self.assertIn('function getCollectionPosterSlots(collection)', app_js)
        self.assertIn('poster_slots:posterSlots', app_js)
        self.assertIn('getCollectionPosterSlots(collection).length >= 1', app_js)
        self.assertIn('if(activePage === "collection-detail")', app_js)
        self.assertIn('applyCollectionDetailFilterState(Object.assign({},current,nextEye));', app_js)
        self.assertIn('function renderMediaPosterPlaceholderHTML(item,media="movie",extraClass="")', ui)
        self.assertIn('function renderPosterTitlePlaceholderHTML(item,media="movie",extraClass="")', ui)
        self.assertIn('function getCollectionPosterSlotsForRender(collection)', ui)
        self.assertIn('collection-stack-placeholder', ui)
        self.assertNotIn('`<div class="genre-card-placeholder">${mediaType === "movie" ? "MOVIE" : "TV"}</div>`', ui)
        self.assertIn('media-title-placeholder', source_css)
        self.assertIn('media-title-placeholder', built_css)
        self.assertIn('collection-stack-placeholder', source_css)
        self.assertIn('collection-stack-placeholder', built_css)

    def test_phase66g1_collection_detail_ui_cleanup_exists(self):
        tmdb_exports = self.read('tvtracker/media/tmdb_exports.py')
        app_js = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')

        self.assertIn('target_count = min(3, max(movie_count, 1))', tmdb_exports)
        self.assertIn('return len(usable_slots) >= target_count', tmdb_exports)
        self.assertIn('tv-tracker-tmdb-collection-index:v6', app_js)
        self.assertIn('tv-tracker-tmdb-collection-detail:v5', app_js)
        self.assertIn('function chooseRicherCollectionSummary(current,next)', app_js)
        self.assertIn('if(!chips.length){ return ""; }', ui)
        self.assertNotIn('if(!chips.length && !eyeActive){ return ""; }', ui)
        self.assertNotIn('.collection-detail-controls .browse-menu > .browse-bar-button', source_css)
        self.assertNotIn('.collection-detail-controls .browse-menu > .browse-bar-button', built_css)

    def test_phase66h_collection_stack_order_and_back_position_exists(self):
        app_js = self.read('static/js/app.js')
        ui = self.read('static/js/ui.js')

        self.assertIn('function orderCollectionPosterSlotsForStack(slots)', ui)
        self.assertIn('return [behind[0],front,behind[1]].filter(Boolean);', ui)
        self.assertIn('collection-stack-placeholder', ui)
        self.assertIn('slot.poster_path ? `<img loading="lazy"', ui)
        self.assertIn('const COLLECTION_RETURN_POSITION_KEY', app_js)
        self.assertIn('function saveCollectionReturnPosition()', app_js)
        self.assertIn('function restoreCollectionReturnPositionSoon(route="",attempt=0)', app_js)
        self.assertIn('document.addEventListener("click",handleCollectionReturnPositionClick,true);', app_js)
        self.assertIn('restoreCollectionReturnPositionSoon(getCollectionsRoute(collectionsPageState));', app_js)




    def test_trailing_slash_redirects_preserve_query_strings(self):
        backend = self.read('tvtracker/web/routes.py')
        app_js = self.read('static/js/app.js')

        self.assertIn('def redirect_app_path_preserving_query(path: str):', backend)
        self.assertIn('request.query_string.decode("utf-8", errors="ignore")', backend)
        self.assertNotIn('return redirect(requested_path)', backend)
        self.assertGreaterEqual(
            backend.count('return redirect_app_path_preserving_query(requested_path)'),
            10,
        )
        self.assertEqual(app_js.count('function canUseTMDBShow(show)'), 1)


if __name__ == '__main__':
    unittest.main()

    def test_phase66g2_collection_slot_hydration_and_spacing_exists(self):
        app_js = self.read('static/js/app.js')
        source_css = self.read('static/css/tailwind-input.css')
        built_css = self.read('static/css/tailwind.css')

        self.assertIn('function collectionNeedsPosterSlotHydration(collection)', app_js)
        self.assertIn('async function hydrateIncompleteCollectionSlots(collections,options={})', app_js)
        self.assertIn('hydrateVisibleCollectionsForIndex().catch(()=>{});', app_js)
        self.assertIn('return hydrateIncompleteCollectionSlots(rowCollections,{limit:rowCollections.length});', app_js)
        self.assertIn('gap:8px;', source_css)
        self.assertIn('gap:8px;', built_css)
        self.assertIn('.movie-release-sort-current', source_css)
        self.assertIn('min-width:0;', source_css)
