const fs = require("fs");
const path = require("path");
const assert = require("assert");

const ROOT = path.resolve(__dirname,"..");
const source = fs.readFileSync(path.join(ROOT,"static/js/notifications-final.js"),"utf8");
const backend = fs.readFileSync(path.join(ROOT,"tvtracker/notifications/push_and_movies.py"),"utf8");
const runtime = fs.readFileSync(path.join(ROOT,"tvtracker/notifications/runtime.py"),"utf8");
const worker = fs.readFileSync(path.join(ROOT,"notification_worker.py"),"utf8");
const wsgi = fs.readFileSync(path.join(ROOT,"wsgi.py"),"utf8");
const deploy = fs.readFileSync(path.join(ROOT,".github/workflows/deploy.yml"),"utf8");

assert(source.includes('"Movie Released"'));
assert(source.includes('"Movie Release Updates"'));
assert(source.includes('"Push Notifications"'));
assert(source.includes('registration.pushManager.subscribe'));
assert(source.includes('pushManager.getSubscription'));
assert(source.includes('subscription.unsubscribe()'));
assert(source.includes('tvtracker-consume-push-clicks'));
assert(source.includes('tvtracker-push-clicks'));
assert(source.includes('/api/push/presence'));
assert(source.includes('dataset.intrinsicDisabled'));
assert(source.includes('notificationApi()'));
assert(source.includes('updateViaCache:"none"'));
assert(source.includes('add TV Tracker to your Home Screen'));
assert(source.includes('isStandaloneDisplay'));
assert(!source.includes('NotificationApi.requestPermission()'));
assert(!source.includes('pushNotification='));

const enableStart = source.indexOf("async function enablePush");
const enableEnd = source.indexOf("async function disablePush",enableStart);
const enableSource = source.slice(enableStart,enableEnd);
const subscribeStatement = "subscription = await registration.pushManager.subscribe";
const subscribePosition = enableSource.indexOf(subscribeStatement);
assert(subscribePosition > 0);
const beforeSubscribe = enableSource.slice(0,subscribePosition).replace(/\/\/.*$/gm,"");
assert(!beforeSubscribe.includes("await "));

assert(backend.includes('MEANINGFUL_MOVIE_RELEASE_TYPES = {2, 3, 4, 6}'));
assert(backend.includes('return f"movie:{movie_id}:{region}:released"'));
assert(backend.includes('silent_release_claim'));
assert(backend.includes("tv_tracker_movie_notification_baseline"));
assert(backend.includes("tv_tracker_push_subscriptions"));
assert(backend.includes("tv_tracker_push_presence"));
assert(backend.includes("tv_tracker_push_deliveries"));
assert(backend.includes("session_version BIGINT NOT NULL DEFAULT 0"));
assert(backend.includes("media_type TEXT NOT NULL DEFAULT 'tv'"));
assert(backend.includes('f"/app/movie/{movie_id}"'));
assert(backend.includes("MAX_PUSHES_PER_BATCH = 3"));
assert(backend.includes("PUSH_ACTIVE_WINDOW_SECONDS = 75"));
assert(backend.includes("PUSH_REQUEST_TIMEOUT_SECONDS = 10"));
assert(backend.includes("timeout=PUSH_REQUEST_TIMEOUT_SECONDS"));
assert(backend.includes("FOR UPDATE OF d SKIP LOCKED"));
assert(backend.includes("PUSH_DELIVERY_RETENTION_DAYS = 30"));
assert(backend.includes("ON CONFLICT (delivery_key) DO NOTHING"));
assert(backend.includes("status_code in {404, 410}"));
assert(backend.includes("VAPID_PRIVATE_KEY"));
assert(backend.includes("VAPID_PUBLIC_KEY"));
assert(backend.includes("VAPID_SUBJECT"));
assert(backend.includes("_best_effort"));
assert(backend.includes("PUSH_DEVICE_COOKIE"));
assert(!backend.toLowerCase().includes('notification_type="renewed"'));
assert(!backend.includes('event_type, "renewed"'));

const swStart = backend.indexOf("def _service_worker_source");
const swEnd = backend.indexOf("def _best_effort",swStart);
const swSource = backend.slice(swStart,swEnd);
assert(swSource.includes('addEventListener("push"'));
assert(swSource.includes('addEventListener("notificationclick"'));
assert(swSource.includes('showNotification'));
assert(swSource.includes('indexedDB.open'));
assert(!swSource.includes('visibilityState'));
assert(!swSource.includes('addEventListener("fetch"'));

assert(runtime.includes("_ORIGINAL_ENSURE_FINAL_SCHEMA"));
assert(runtime.includes("final.ensure_final_schema = _schema_already_prepared"));
assert(!runtime.includes("final.run_movie_notification_check ="));
assert(!runtime.includes("final._claim_push_batch ="));
assert(runtime.includes("run_final_notification_worker_hardened"));
assert(runtime.includes("DELETE FROM tv_tracker_movie_notification_baseline"));
assert(runtime.includes("d.status IN ('pending', 'retry')"));
assert(runtime.includes("attempts >= %s"));
assert(runtime.includes("status = 'failed'"));
assert(runtime.includes("device active before delivery"));
assert(worker.includes("run_final_notification_worker_hardened"));
assert(wsgi.includes("prepare_final_notification_runtime"));
assert(deploy.includes('pip install $PIP_SCOPE -r requirements.txt'));
assert(deploy.includes('import pywebpush'));

console.log("Final notifications browser/source contracts passed.");
