<script setup lang="ts">
import { computed, ref, watch, onMounted, onBeforeUnmount } from 'vue';
import type { BrowseActions, BrowseControlsModel, BrowseMenu } from './browseViewModel';
import type { CollectionEyeKey } from './collectionViewModel';
import BrowseIcon from './BrowseIcon.vue';
import BrowsePicker from './BrowsePicker.vue';
const props = defineProps<{model: BrowseControlsModel; actions: BrowseActions}>();
const root = ref<HTMLElement | null>(null);
const searches = ref<Record<string,string>>({});
const decade = ref(props.model.selectedDecade);
const yearMenu = ref<HTMLDetailsElement | null>(null);
const decades = computed(() => Array.from({length:(props.model.currentDecade-1870)/10+1},(_,i)=>props.model.currentDecade-i*10));
const years = computed(() => Array.from({length:10},(_,i)=>decade.value+i));
const eyes: readonly {key:CollectionEyeKey;label:string}[] = [{key:'fadeWatched',label:'Fade watched'},{key:'hideWatched',label:'Hide watched'},{key:'hidePlan',label:'Hide Plan to Watch'},{key:'hideFavorites',label:'Hide Favorites'}];
watch(() => props.model.selectedDecade, value => {decade.value=value;});
function filtered(menu: BrowseMenu) { const query = (searches.value[menu.key] || '').trim().toLowerCase(); return menu.choices.filter(item => !query || (item.search || item.label).toLowerCase().includes(query)); }
function close(except?: HTMLDetailsElement) { root.value?.querySelectorAll<HTMLDetailsElement>('details[open]').forEach(menu=>{if(menu!==except)menu.open=false;}); }
function summary(event: MouseEvent) { const menu=(event.currentTarget as HTMLElement).parentElement as HTMLDetailsElement; close(menu); }
function outside(event: PointerEvent) { if(event.target instanceof Node && !root.value?.contains(event.target))close(); }
function keyboard(event: KeyboardEvent) { if(event.key==='Escape')close(); }
onMounted(()=>{document.addEventListener('pointerdown',outside);document.addEventListener('keydown',keyboard);});
onBeforeUnmount(()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',keyboard);});
function selectDecade(value: number) { decade.value=value; close(); void props.actions.choose({key:'decade',value:String(value),label:`${value}s`,selected:false}); }
function showDecades() { decade.value=0; close(); if(yearMenu.value)yearMenu.value.open=true; }
</script>
<template>
  <div ref="root" class="browse-controls" @click.stop @input.stop>
    <div class="browse-bar" aria-label="Browse filters">
      <span class="browse-bar-kicker">BROWSE BY</span>
      <details ref="yearMenu" class="browse-menu browse-menu-year"><summary class="browse-bar-button" @click="summary">{{ model.yearLabel }} <BrowseIcon /></summary><div class="browse-dropdown browse-dropdown-year"><div class="browse-year-decade-menu"><div class="browse-option-list">
        <button type="button" class="browse-dropdown-option" :class="{selected:!model.year&&!model.selectedDecade&&!model.upcoming}" @click="actions.choose({key:'year',value:'',label:'Any',selected:false})">Any</button>
        <button type="button" class="browse-dropdown-option" :class="{selected:model.upcoming}" @click="actions.choose({key:'upcoming',value:'1',label:'Upcoming',selected:false})">Upcoming</button>
      </div><div class="browse-dropdown-divider"></div><div class="browse-option-list browse-year-decade-list"><button v-for="value in decades" :key="value" type="button" class="browse-dropdown-option browse-decade-list-option" :class="{selected:model.selectedDecade===value}" :aria-pressed="model.selectedDecade===value" @click="selectDecade(value)"><span>{{ value }}s</span><span class="browse-decade-list-icons"><BrowseIcon v-if="model.selectedDecade===value" kind="check" /><BrowseIcon kind="right" /></span></button></div></div></div></details>
      <details v-for="menu in model.menus.filter(menu=>menu.key!=='sort')" :key="menu.key" class="browse-menu" :class="`browse-menu-${menu.key}`"><summary class="browse-bar-button" @click="summary">{{ menu.label }} <BrowseIcon /></summary><div class="browse-dropdown" :class="`browse-dropdown-${menu.key}`">
        <input v-if="menu.searchLabel" v-model="searches[menu.key]" class="browse-dropdown-search" type="search" :placeholder="menu.searchLabel" :aria-label="menu.searchLabel">
        <div class="browse-option-list" :class="`browse-${menu.key}-option-list`"><button v-for="choice in filtered(menu)" :key="choice.value" type="button" class="browse-dropdown-option" :class="{selected:choice.selected,'browse-service-option':menu.key==='service'}" :aria-pressed="choice.selected" @click="actions.choose(choice)"><span v-if="menu.key==='service'" class="browse-service-option-main"><span class="browse-service-logo-tile" :class="{'browse-service-logo-fallback':!choice.logo}"><img v-if="choice.logo" class="browse-service-logo" :src="choice.logo" alt=""><template v-else>TV</template></span><span>{{ choice.label }}</span></span><span v-else>{{ choice.label }}</span><BrowseIcon v-if="choice.selected" kind="check" /></button><div v-if="!menu.choices.length" class="browse-dropdown-empty">{{ menu.empty }}</div></div>
      </div></details>
      <details class="browse-menu browse-menu-other"><summary class="browse-bar-button" @click="summary">OTHER <BrowseIcon /></summary><div class="browse-dropdown browse-dropdown-other"><BrowsePicker type="theme" :selected="model.selectedPickers.theme" :actions="actions" /><div class="browse-dropdown-divider"></div><BrowsePicker type="company" :selected="model.selectedPickers.company" :actions="actions" /><template v-if="model.media==='tv'"><div class="browse-dropdown-divider"></div><BrowsePicker type="network" :selected="model.selectedPickers.network" :actions="actions" /></template><div class="browse-dropdown-divider"></div><div class="browse-other-section"><span class="browse-other-heading">{{ model.media==='tv' ? 'Status' : 'US Certification' }}</span><div class="browse-option-list"><button v-for="choice in model.otherChoices" :key="choice.value" type="button" class="browse-dropdown-option" :class="{selected:choice.selected}" :aria-pressed="choice.selected" @click="actions.choose(choice)"><span>{{ choice.label }}</span><BrowseIcon v-if="choice.selected" kind="check" /></button></div></div></div></details>
      <details v-for="menu in model.menus.filter(menu=>menu.key==='sort')" :key="menu.key" class="browse-menu" :class="`browse-menu-${menu.key}`"><summary class="browse-bar-button" @click="summary">{{ menu.label }} <BrowseIcon /></summary><div class="browse-dropdown" :class="`browse-dropdown-${menu.key}`">
        <input v-if="menu.searchLabel" v-model="searches[menu.key]" class="browse-dropdown-search" type="search" :placeholder="menu.searchLabel" :aria-label="menu.searchLabel">
        <div class="browse-option-list" :class="`browse-${menu.key}-option-list`"><button v-for="choice in filtered(menu)" :key="choice.value" type="button" class="browse-dropdown-option" :class="{selected:choice.selected,'browse-service-option':menu.key==='service'}" :aria-pressed="choice.selected" @click="actions.choose(choice)"><span v-if="menu.key==='service'" class="browse-service-option-main"><span class="browse-service-logo-tile" :class="{'browse-service-logo-fallback':!choice.logo}"><img v-if="choice.logo" class="browse-service-logo" :src="choice.logo" alt=""><template v-else>TV</template></span><span>{{ choice.label }}</span></span><span v-else>{{ choice.label }}</span><BrowseIcon v-if="choice.selected" kind="check" /></button><div v-if="!menu.choices.length" class="browse-dropdown-empty">{{ menu.empty }}</div></div>
      </div></details>
      <details class="browse-menu eye-filter-menu browse-eye-filter-menu"><summary class="browse-bar-button eye-filter-button" aria-label="Tracked filters" @click="summary"><img :src="eyes.some(eye=>model.eyes[eye.key]) ? '/static/assets/icons/eye-closed.png' : '/static/assets/icons/eye-open.png'" alt="" aria-hidden="true" class="eye-filter-icon"></summary><div class="browse-dropdown eye-filter-dropdown"><div class="browse-option-list"><button v-for="eye in eyes" :key="eye.key" type="button" class="browse-dropdown-option eye-filter-option" :class="{selected:model.eyes[eye.key]}" :aria-pressed="model.eyes[eye.key]" @click="actions.toggleEye(eye.key)"><span>{{ eye.label }}</span><BrowseIcon v-if="model.eyes[eye.key]" kind="check" /></button></div></div></details>
    </div>
    <div v-if="decade" class="browse-year-secondary-bar"><div class="browse-year-strip"><button type="button" class="browse-decade-nav browse-decade-nav-prev" aria-label="Previous decade" :disabled="decade<=1870" @click="decade-=10"><BrowseIcon kind="left" /></button><button type="button" class="browse-decade-current" aria-label="Back to decades" @click="showDecades">{{ decade }}s</button><div class="browse-year-strip-years"><button v-for="year in years" :key="year" type="button" class="browse-year-strip-year" :class="{selected:model.year===String(year)}" :aria-pressed="model.year===String(year)" @click="actions.choose({key:'year',value:String(year),label:String(year),selected:false})"><span>{{ year }}</span><BrowseIcon v-if="model.year===String(year)" kind="check" /></button></div><button type="button" class="browse-decade-nav browse-decade-nav-next" aria-label="Next decade" :disabled="decade>=model.currentDecade" @click="decade+=10"><BrowseIcon kind="right" /></button></div></div>
    <div v-if="model.showClear" class="browse-active-row" aria-label="Active browse filters"><button v-for="chip in model.chips" :key="`${chip.key}:${chip.value}`" type="button" class="browse-active-chip" @click="actions.remove(chip)">{{ chip.label }} <span aria-hidden="true">×</span></button><button type="button" class="browse-clear-button" @click="actions.clear">CLEAR ALL</button></div>
  </div>
</template>
