"""Authentication domain: session checks, admin account cache, security-event rate limiting, CSRF, and password hashing."""

from tvtracker.auth.security import (
    ACCOUNT_CHANGE_MAX_ATTEMPTS,
    ACCOUNT_CHANGE_WINDOW_SECONDS,
    ADMIN_ACCOUNT_CACHE,
    ADMIN_ACCOUNT_CACHE_AT,
    ADMIN_ACCOUNT_CACHE_TTL_SECONDS,
    ADMIN_ACCOUNT_LOCK,
    LOGIN_MAX_ATTEMPTS,
    LOGIN_WINDOW_SECONDS,
    MIN_ADMIN_PASSWORD_CHARS,
    PASSWORD_HASHER,
    account_change_is_limited,
    check_csrf,
    clear_login_failures,
    clear_security_events,
    client_key,
    invalidate_admin_account_cache,
    is_authenticated,
    login_is_limited,
    login_required,
    read_admin_account,
    record_login_failure,
    record_security_event,
    security_event_count,
)

__all__ = [
    "ACCOUNT_CHANGE_MAX_ATTEMPTS",
    "ACCOUNT_CHANGE_WINDOW_SECONDS",
    "ADMIN_ACCOUNT_CACHE",
    "ADMIN_ACCOUNT_CACHE_AT",
    "ADMIN_ACCOUNT_CACHE_TTL_SECONDS",
    "ADMIN_ACCOUNT_LOCK",
    "LOGIN_MAX_ATTEMPTS",
    "LOGIN_WINDOW_SECONDS",
    "MIN_ADMIN_PASSWORD_CHARS",
    "PASSWORD_HASHER",
    "account_change_is_limited",
    "check_csrf",
    "clear_login_failures",
    "clear_security_events",
    "client_key",
    "invalidate_admin_account_cache",
    "is_authenticated",
    "login_is_limited",
    "login_required",
    "read_admin_account",
    "record_login_failure",
    "record_security_event",
    "security_event_count",
]
